# -*- coding: utf-8 -*-
"""rl_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Pbarbecho/Curso_Python/blob/main/control/ejercicios/rl_1.ipynb
"""

# Required package
#!pip install sympy
#!pip install control

import numpy as np
from sympy import *
import control
import matplotlib.pyplot as plt

# Gain K , Unitary Gain k=1
K=1

# Declare polynomials
s = Symbol('s')

expr_num = K*s+K*2 # include K
expr_den = s**2+2*s+3

poly_num = poly(expr_num)
poly_den = poly(expr_den)

# Get denominator's coefficients
num_sp = poly_num.all_coeffs()
den_sp = poly_den.all_coeffs()

num = [int(i) for i in num_sp]
den = [int(i) for i in den_sp]

# Open Loop Transfer Function
OLTF = control.tf(num,den)
print(OLTF)

# OLTF Poles
plt.figure(1)
control.pzmap(OLTF, False)

# Root locus
plt.figure(2)
control.rlocus(OLTF, xlim=(-4, 0), print_gain=True)


# Close Loop Transfer Function (CLTF)
CLTF = control.feedback(OLTF,1)
print(CLTF)

# CLTF Poles
plt.figure(3)
control.pzmap(CLTF, True)

y,x = control.step_response(CLTF)
plt.figure(4)
plt.plot(y,x)
plt.title("Step Response")

plt.show()


